# Generated by Django 4.0.5 on 2022-07-08 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_auth', '0002_alter_user_managers_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
