# Generated by Django 4.0.5 on 2022-07-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_auth', '0003_remove_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationExtraFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('exam', models.CharField(choices=[('jee', 'JEE'), ('cet', 'CET'), ('jee_adv', 'JEE Advanced'), ('neet', 'NEET'), ('others', 'Others')], default='others', max_length=20)),
                ('social_media', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('twitter', 'twitter'), ('none', 'None')], default='none', max_length=20)),
            ],
        ),
    ]
