# Generated by Django 4.0.5 on 2022-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_auth', '0004_userregistrationextrafields'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationExtraFields',
        ),
        migrations.AddField(
            model_name='user',
            name='exam',
            field=models.CharField(choices=[('jee', 'JEE'), ('cet', 'CET'), ('jee_adv', 'JEE Advanced'), ('neet', 'NEET'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='social_media',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'Linkedin'), ('twitter', 'twitter'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
